### ISSUE TITLE
[Feature Request] Add some Option to :

### ISSUE THREAD

**Issue by ardissaps** [Cynosphere-mc/Scout#1]
Hello thank you for the great mods!

Would you like to add option for :
- Disable Custom Color GUI (choice to use normal/dark mode etc)
- Render Equiped Satchel on Body
- Move the left-side sachel when Opening Vanilla/Modded RecipeBook (https://modrinth.com/mod/brb)
![image](https://user-images.githubusercontent.com/82106625/174725959-0e5dbebd-adfb-4ed3-b07c-c755bc965f1c.png)

- Accept modded material for recipe (use tag or similiar)

**Comment by Balakay420** [comment]
@ardissaps where'd ya get the Dark GUI???

**Comment by ardissaps** [comment]
Vanilla : https://www.curseforge.com/minecraft/texture-packs/default-dark-mode
Modded : https://www.curseforge.com/minecraft/texture-packs/darkmode-mod-support-fabric
When Not Available : I just edited the lightness in Photoshop. (look awkward sometimes but healthy for our eyes)

**Comment by Cynosphere** [comment]
> Disable Custom Color GUI (choice to use normal/dark mode etc)

I originally intended to put the colors into the texture and then thought about potentially adding dyeing in the future.
You can still modify the texture at [`scout:textures/gui/slots.png`](https://github.com/Cynosphere-mc/Scout/blob/main/platform-1.18/src/main/resources/assets/scout/textures/gui/slots.png) if you need it to be darker. I would make this configurable but I don't want to lock it as a Quilt-only mod since Quilt has a one size fits all solution to configuration.

> Render Equiped Satchel on Body

Planned

> Move the left-side sachel when opening recipe book

I completely forgot about this before releasing the mod because of the fact I don't personally use it. I will probably move the book over or just hide the pouch because moving the pouch isn't an option because it overlaps the crafting grid, otherwise it would be sticking out further than the other pouch. Its why I made upgraded pouches have two columns in the first place.

> Accept modded material for recipe (use tag or similiar)

Will fix. I was originally going to add Tanned Leather to `c:leather` itself but decided against it.

**Comment by ardissaps** [comment]
Take your time, not in a hurry, it already super functional right now. Thank you very much!
